import type { Dish, MenuCategory } from "./contract";

/**
 * Données de démonstration du service.
 * Elles remplacent la base de données tant qu'il n'y a pas de backend :
 * le jour où il arrive, seul ce fichier disparaît.
 */
export const categories: readonly MenuCategory[] = [
  { id: "entrees", label: "Entrées", tagline: "Pour commencer, doucement.", order: 1 },
  { id: "plats", label: "Plats", tagline: "Le cœur de la maison.", order: 2 },
  { id: "desserts", label: "Desserts", tagline: "La dernière page, la plus lue.", order: 3 },
  { id: "brunch", label: "Brunch", tagline: "Samedi et dimanche, jusqu'à 15h.", order: 4 },
  { id: "bar", label: "Bar", tagline: "Au comptoir, sans réservation.", order: 5 },
];

export const dishes: readonly Dish[] = [
  {
    id: "dish_001",
    slug: "assiette-du-marche",
    name: "Assiette du marché",
    description:
      "Le trio du jour selon les arrivages : tataki de bœuf, croustillant de cabillaud et lentilles vertes du Puy.",
    priceCents: 1600,
    currency: "EUR",
    categoryId: "entrees",
    image: {
      src: "/media/dishes/assiette-du-marche.jpg",
      alt: "Trois assiettes composées de l'entrée du marché vues de dessus",
    },
    tags: ["de-saison", "a-partager"],
    allergens: ["poisson", "sulfites"],
    origin: "Marché d'Aligre, Paris 12e",
    available: true,
  },
  {
    id: "dish_002",
    slug: "salade-des-vignerons",
    name: "Salade des vignerons",
    description:
      "Mesclun, feta de brebis, noix du Périgord, raisins noirs et vinaigrette au verjus.",
    priceCents: 1400,
    currency: "EUR",
    categoryId: "entrees",
    image: {
      src: "/media/dishes/salade-des-vignerons.jpg",
      alt: "Salade composée servie dans une assiette noire",
    },
    tags: ["vegetarien", "de-saison"],
    allergens: ["lait", "fruits à coque"],
    origin: "Noix de Sarlat AOP",
    available: true,
  },
  {
    id: "dish_003",
    slug: "croustillant-de-chevre",
    name: "Croustillant de chèvre",
    description:
      "Chèvre frais pané aux graines, miel de châtaignier, roquette et pain grillé au levain.",
    priceCents: 1300,
    currency: "EUR",
    categoryId: "entrees",
    image: {
      src: "/media/dishes/croustillant-de-chevre.jpg",
      alt: "Croustillants de chèvre chaud accompagnés de salade",
    },
    tags: ["vegetarien"],
    allergens: ["gluten", "lait", "œuf"],
    origin: "Chèvrerie du Vexin",
    available: true,
  },
  {
    id: "dish_004",
    slug: "focaccia-du-four",
    name: "Focaccia du four",
    description:
      "Pâte levée maison, fior di latte fondue, oignons rouges confits, herbes fraîches et huile de Nyons.",
    priceCents: 1500,
    currency: "EUR",
    categoryId: "entrees",
    image: {
      src: "/media/dishes/focaccia-du-four.jpg",
      alt: "Focaccia dorée garnie de fromage fondu et d'oignons rouges, découpée sur une planche",
    },
    tags: ["vegetarien", "a-partager"],
    allergens: ["gluten", "lait"],
    origin: null,
    available: true,
  },
  {
    id: "dish_005",
    slug: "entrecote-frites",
    name: "Entrecôte, frites maison",
    description:
      "300 g de race Aubrac maturée 30 jours, beurre d'estragon, frites coupées à la main.",
    priceCents: 3200,
    currency: "EUR",
    categoryId: "plats",
    image: {
      src: "/media/dishes/entrecote-frites.jpg",
      alt: "Entrecôte grillée et frites maison dans une assiette blanche",
    },
    tags: ["signature"],
    allergens: ["lait"],
    origin: "Élevage Aubrac, Aveyron",
    available: true,
  },
  {
    id: "dish_006",
    slug: "cote-de-cochon",
    name: "Côte de cochon fermier",
    description:
      "Porc noir de Bigorre, pommes rôties au thym, brocolis et jus court au cidre fermier.",
    priceCents: 2800,
    currency: "EUR",
    categoryId: "plats",
    image: {
      src: "/media/dishes/cote-de-cochon.jpg",
      alt: "Côte de cochon rôtie avec pommes et brocolis",
    },
    tags: ["signature", "de-saison"],
    allergens: ["sulfites"],
    origin: "Noir de Bigorre AOP, Hautes-Pyrénées",
    available: true,
  },
  {
    id: "dish_007",
    slug: "farfalle-pistache",
    name: "Farfalle au pesto de pistache",
    description:
      "Pâtes fraîches du jour, pesto de pistache de Bronte, tomates confites et pecorino.",
    priceCents: 2200,
    currency: "EUR",
    categoryId: "plats",
    image: {
      src: "/media/dishes/farfalle-pistache.jpg",
      alt: "Farfalle au pesto vert avec tomates cerises",
    },
    tags: ["vegetarien"],
    allergens: ["gluten", "lait", "fruits à coque"],
    origin: "Pistache de Bronte DOP, Sicile",
    available: true,
  },
  {
    id: "dish_008",
    slug: "burger-lumiere",
    name: "Le Burger Lumière",
    description:
      "Bœuf maturé haché minute, comté 18 mois, oignons confits, pain brioché maison et frites.",
    priceCents: 2400,
    currency: "EUR",
    categoryId: "plats",
    image: {
      src: "/media/dishes/burger-lumiere.jpg",
      alt: "Burger maison servi avec un panier de frites",
    },
    tags: [],
    allergens: ["gluten", "lait", "œuf", "moutarde"],
    origin: null,
    available: true,
  },
  {
    id: "dish_009",
    slug: "gratin-du-marche",
    name: "Gratin du marché",
    description:
      "Légumes de saison, béchamel au parmesan, herbes fraîches et gremolata au citron.",
    priceCents: 2100,
    currency: "EUR",
    categoryId: "plats",
    image: {
      src: "/media/dishes/gratin-du-marche.jpg",
      alt: "Gratin de légumes et accompagnements sur une table en marbre",
    },
    tags: ["vegetarien", "de-saison"],
    allergens: ["gluten", "lait"],
    origin: null,
    available: true,
  },
  {
    id: "dish_010",
    slug: "travers-laques",
    name: "Travers de bœuf laqués",
    description:
      "Huit heures de cuisson lente, laque au poivre de Timut, cornichons maison et pain grillé.",
    priceCents: 2900,
    currency: "EUR",
    categoryId: "plats",
    image: {
      src: "/media/dishes/travers-laques.jpg",
      alt: "Travers de bœuf laqués servis sur une planche",
    },
    tags: ["epice"],
    allergens: ["gluten", "soja", "sésame"],
    origin: "Poivre de Timut, Népal",
    available: true,
  },
  {
    id: "dish_011",
    slug: "bol-du-midi",
    name: "Le Bol du midi",
    description:
      "Tofu grillé au tamari, edamame, maïs doux, légumes croquants et sauce sésame. Service du déjeuner uniquement.",
    priceCents: 1700,
    currency: "EUR",
    categoryId: "plats",
    image: {
      src: "/media/dishes/bol-du-midi.jpg",
      alt: "Bol composé de tofu grillé, edamame et légumes frais",
    },
    tags: ["vegan", "sans-gluten"],
    allergens: ["soja", "sésame"],
    origin: null,
    available: true,
  },
  {
    id: "dish_012",
    slug: "pain-perdu",
    name: "Pain perdu de la brioche",
    description:
      "Brioche maison de la veille, banane caramélisée, myrtilles et glace vanille de Madagascar.",
    priceCents: 1200,
    currency: "EUR",
    categoryId: "desserts",
    image: {
      src: "/media/dishes/pain-perdu.jpg",
      alt: "Pain perdu doré à la banane et aux myrtilles",
    },
    tags: ["signature"],
    allergens: ["gluten", "lait", "œuf"],
    origin: null,
    available: true,
  },
  {
    id: "dish_013",
    slug: "framboise-pistache",
    name: "Framboise-pistache",
    description:
      "Biscuit moelleux à la pistache, crème légère vanillée et framboises de Sologne.",
    priceCents: 1300,
    currency: "EUR",
    categoryId: "desserts",
    image: {
      src: "/media/dishes/framboise-pistache.jpg",
      alt: "Part de gâteau framboise-pistache sur une assiette noire",
    },
    tags: ["de-saison"],
    allergens: ["gluten", "lait", "œuf", "fruits à coque"],
    origin: "Framboises de Sologne",
    available: true,
  },
  {
    id: "dish_014",
    slug: "grand-brunch",
    name: "Le Grand Brunch",
    description:
      "Formule complète : œufs façon bénédicte, gaufre, corbeille de pains, fruits frais, jus pressé et café.",
    priceCents: 3400,
    currency: "EUR",
    categoryId: "brunch",
    image: {
      src: "/media/dishes/brunch-complet.jpg",
      alt: "Table de brunch garnie de gaufres, œufs et jus d'orange",
    },
    tags: ["signature", "a-partager"],
    allergens: ["gluten", "lait", "œuf"],
    origin: null,
    available: true,
  },
  {
    id: "dish_015",
    slug: "gaufres-dimanche",
    name: "Gaufres du dimanche",
    description: "Gaufres de Liège au sucre perlé, fruits rouges et chantilly au mascarpone.",
    priceCents: 1400,
    currency: "EUR",
    categoryId: "brunch",
    image: {
      src: "/media/dishes/gaufres-dimanche.jpg",
      alt: "Gaufres et petits plats de brunch vus de dessus",
    },
    tags: ["vegetarien"],
    allergens: ["gluten", "lait", "œuf"],
    origin: null,
    available: true,
  },
  {
    id: "dish_016",
    slug: "pancakes-erable",
    name: "Pancakes, sirop d'érable",
    description:
      "Pancakes moelleux empilés, banane fraîche, menthe et sirop d'érable ambré du Québec.",
    priceCents: 1200,
    currency: "EUR",
    categoryId: "brunch",
    image: {
      src: "/media/dishes/pancakes-maison.jpg",
      alt: "Pile de pancakes nappée de sirop d'érable",
    },
    tags: ["vegetarien"],
    allergens: ["gluten", "lait", "œuf"],
    origin: "Érablière de l'Estrie, Québec",
    available: true,
  },
  {
    id: "dish_017",
    slug: "vieux-carre",
    name: "Vieux Carré",
    description:
      "Rye, cognac, vermouth rouge, Bénédictine et deux traits d'amers. Remué, jamais secoué.",
    priceCents: 1400,
    currency: "EUR",
    categoryId: "bar",
    image: {
      src: "/media/dishes/vieux-carre.jpg",
      alt: "Cocktail ambré servi sur un gros glaçon",
    },
    tags: ["signature"],
    allergens: ["sulfites"],
    origin: null,
    available: true,
  },
  {
    id: "dish_018",
    slug: "spritz-maison",
    name: "Spritz maison",
    description:
      "Notre amer infusé à la gentiane, vin blanc pétillant et zeste d'orange sanguine.",
    priceCents: 1100,
    currency: "EUR",
    categoryId: "bar",
    image: null,
    tags: ["vegan"],
    allergens: ["sulfites"],
    origin: null,
    available: true,
  },
  {
    id: "dish_019",
    slug: "verre-du-mois",
    name: "Le verre du mois",
    description: "Sancerre blanc, Domaine Vacheron. Au verre 9 €, la bouteille 42 €.",
    priceCents: 900,
    currency: "EUR",
    categoryId: "bar",
    image: null,
    tags: ["de-saison"],
    allergens: ["sulfites"],
    origin: "Sancerre, Val de Loire",
    available: true,
  },
  {
    id: "dish_020",
    slug: "cafe-de-specialite",
    name: "Café de spécialité",
    description: "Torréfaction artisanale parisienne, en filtre lent ou en espresso serré.",
    priceCents: 400,
    currency: "EUR",
    categoryId: "bar",
    image: null,
    tags: ["vegan", "sans-gluten"],
    allergens: [],
    origin: "Torréfacteur de Belleville, Paris 11e",
    available: true,
  },
];

export const menuUpdatedAt = "2026-09-01T09:00:00.000Z";
